apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
  - name: test-pod
    image: alpine:3.8
    imagePullPolicy: Always
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]

